stages:
  - debug
  - deploy

variables:
  BRANCH: technical-33-geautomatiseerde-deployment-omgeving

debug:
  stage: debug
  tags:
    - docker_deployment
  script:
    - echo "Current branch $CI_COMMIT_BRANCH"
    - echo "Pipeline source $CI_PIPELINE_SOURCE"
    - echo "Commit SHA $CI_COMMIT_SHA"

deploy:
  stage: deploy
  tags:
    - docker_deployment
  script:
    - echo "Current branch $CI_COMMIT_BRANCH"
    - echo "Expected branch $BRANCH"
    - docker --version 
    - docker compose --version
    - docker compose up -d --build 
  rules:
    - if: '$CI_COMMIT_BRANCH == $BRANCH && $CI_PIPELINE_SOURCE == "tag"'
