stages:
  - deploy

deploy_main:
    stage: deploy
    tags:
    - deployment
    script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker-compose pull
    - docker-compose down
    - docker-compose up -d
    only:
        refs:
        - tags
        variables:
        - $CI_COMMIT_REF_NAME == "main"

