stages:
  - deploy
variables:
  BRANCH: technical-33-geautomatiseerde-deployment-omgeving
deploy:
  stage: deploy
  script:
    - docker-compose up -d
  rules:
    - if: '$CI_COMMIT_BRANCH == $BRANCH && $CI_PIPELINE_SOURCE == "tag"'
