stages:
  - deploy
variables:
  BRANCH: technical-33-geautomatiseerde-deployment-omgeving
deploy:
  stage: deploy
  script:
    - echo "Current branch: $CI_COMMIT_BRANCH"
    - echo "Expected branch: $BRANCH"
    - docker-compose up -d --build 
  rules:
    - if: '$CI_COMMIT_BRANCH == $BRANCH && $CI_PIPELINE_SOURCE == "tag"'
