stages:
  - deploy
deploy_main:
    stage: deploy
    tags:
    - docker_deployment
    script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker-compose pull
    - docker-compose down
    - docker-compose up -d
    rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "technical-33-geautomatiseerde-deployment-omgeving"'
      when: never

