stages:
  - production-deployment
  - staging-deployment

production-deploy:
  stage: production-deployment
  tags:
    - production
  script:
    - cp /etc/gatam/.env.production ${CI_PROJECT_DIR}/'ASP - GATAM ISW-IP'/.env.production
    - cd './ASP - GATAM ISW-IP/'
    - docker compose --env-file .env.production -p production -f docker-compose.production.yml down
    - docker compose --env-file .env.production -p production -f docker-compose.production.yml up -d --build 
  rules:
    - if: '$CI_COMMIT_TAG'
  environment: production
staging-deploy:
  stage: staging-deployment
  tags:
    - staging
  script:
    - cp /etc/gatam/.env.staging ${CI_PROJECT_DIR}/'ASP - GATAM ISW-IP'/.env.staging
    - cd './ASP - GATAM ISW-IP/'
    - docker compose --env-file .env.staging -p staging -f docker-compose.staging.yml down
    - docker compose --env-file .env.staging -p staging -f docker-compose.staging.yml up -d --build 
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: always
  environment: staging
