stages:
  - debug
  - deploy

variables:
  BRANCH: technical-33-geautomatiseerde-deployment-omgeving

debug:
  stage: debug
  tags:
    - docker_deployment
  script:
    - echo "Current branch $CI_COMMIT_BRANCH"
    - echo "Pipeline source $CI_PIPELINE_SOURCE"
    - echo "Commit SHA $CI_COMMIT_SHA"
    - echo "Commit TAG $CI_COMMIT_TAG"

deploy:
  stage: deploy
  tags:
    - docker_deployment
  script:
    - echo "Current branch $CI_COMMIT_BRANCH"
    - echo "Expected branch $BRANCH"
    - docker --version 
    - docker compose --version
    - cd './ASP - GATAM ISW-IP/' && docker compose up -d --build 
  rules:
    - if: '$CI_COMMIT_TAG'
