version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"  # Vervang dit door een sterk wachtwoord
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: ./Presentation/Gatam.WebAPI
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "5001:443"
    depends_on:
      - sqlserver

  frontend:
    build:
      context: ./Presentation/Gatam.WebAppBegeleider
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
      - "5003:443" 
    depends_on:
      - backend
  frontend_2:
    build:
      context: ./Presentation/Gatam.WebAppVolger
      dockerfile: Dockerfile
    ports:
      - "5004:8080"
      - "5005:443" 
    depends_on:
      - backend

volumes:
  sql_data:
