services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    container_name: "${ENVIRONMENT}-mssql"
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA="Y"
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_NAME=Gatam.${ENVIRONMENT}
    networks:
      - database
    hostname: mssqlserver
  webapi:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAPI/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-api
    ports:
      - "5000:8080"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Logging__Loglevel__Default=Debug
      - Logging__Loglevel__Microsoft.AspNetCore=Debug
    depends_on:
      - mssql-server
    networks:
      - database
      - staging-proxy
  webappbegeleider:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAppBegeleider/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-webappbegeleider
    ports:
      - "5002:8080"
      - "5003:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Logging__Loglevel__Default=Debug
      - Logging__Loglevel__Microsoft.AspNetCore=Debug
    depends_on:
      - webapi
      - mssql-server
    networks:
      - database
      - staging-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webappbegeleider.entrypoints=http"
      - "traefik.http.routers.webappbegeleider.rule=Host(`staging-gatam-beheer.nilsvanvaerenbergh.be`)"
      - "traefik.http.middlewares.webappbegeleider-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.webappbegeleider.middlewares=traefik-https-redirect"
      - "traefik.http.routers.webappbegeleider-secure.entrypoints=https"
      - "traefik.http.routers.webappbegeleider-secure.rule=Host(`staging-gatam-beheer.nilsvanvaerenbergh.be`)"
      - "traefik.http.routers.webappbegeleider-secure.tls=true"
      - "traefik.http.routers.webappbegeleider-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.webappbegeleider-secure.tls.domains[0].main=nilsvanvaerenbergh.be"
      - "traefik.http.routers.webappbegeleider-secure.tls.domains[0].sans=staging-gatam-beheer.nilsvanvaerenbergh.be"
  webappvolger:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAppVolger/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-webappvolger
    ports:
      - "8080"
      - "443"
    depends_on:
      - webapi
      - mssql-server
    networks:
      - database
      - staging-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webappvolger.entrypoints=http"
      - "traefik.http.routers.webappvolger.rule=Host(`staging-gatam.nilsvanvaerenbergh.be`)"
      - "traefik.http.middlewares.webappvolger-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.webappvolger.middlewares=traefik-https-redirect"
      - "traefik.http.routers.webappvolger-secure.entrypoints=https"
      - "traefik.http.routers.webappvolger-secure.rule=Host(`staging-gatam.nilsvanvaerenbergh.be`)"
      - "traefik.http.routers.webappvolger-secure.tls=true"
      - "traefik.http.routers.webappvolger-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.webappvolger-secure.tls.domains[0].main=nilsvanvaerenbergh.be"
      - "traefik.http.routers.webappvolger-secure.tls.domains[0].sans=staging-gatam.nilsvanvaerenbergh.be"
volumes:
  sql_data:
networks:
  database:
  staging-proxy:
    driver: bridge 
    external: true 