services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"
    env_file:
      - .env
    networks:
      - database
    hostname: mssqlserver
  webapi:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAPI/Dockerfile
    ports:
      - "5000:8080"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Logging__Loglevel__Default=Debug
      - Logging__Loglevel__Microsoft.AspNetCore=Debug
    depends_on:
      - mssql-server
    networks:
      - database
  webappbegeleider:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAppBegeleider/Dockerfile
    ports:
      - "5002:8080"
      - "5003:443"
    depends_on:
      - webapi
      - mssql-server
    networks:
      - database
  webauth:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.Authentication/Dockerfile
    ports:
      - "5006:8080"
      - "5007:443"
    depends_on:
      - webapi
      - mssql-server
    networks:
      - database
  webappvolger:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAppVolger/Dockerfile
    ports:
      - "5004:8080"
      - "5005:443"
    depends_on:
      - webapi
      - mssql-server
    networks:
      - database
volumes:
  sql_data:
networks:
  database:
   driver: bridge 
