services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${ENVIRONMENT}-mssql
    restart: always
    ports: 
      - "1433"
    environment:
      - ACCEPT_EULA="Y"
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_NAME=Gatam.${ENVIRONMENT}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - SA_PASSWORD=${SA_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
    networks:
      - database
    hostname: mssqlserver
  webapi:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAPI/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-api
    ports:
      - "8080"
      - "443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DATABASE_NAME=Gatam.${ENVIRONMENT}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - SA_PASSWORD=${SA_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - TOKEN=${TOKEN}
      - BASE_URI=${BASE_URI}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENTID=${AUTH0_CLIENTID}
      - AUTH0_CLIENTSECRET=${AUTH0_CLIENTSECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    depends_on:
      - mssql-server
    networks:
      - database
      - production-proxy
  webappbegeleider:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAppBegeleider/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-webappbegeleider
    ports:
      - "8080"
      - "443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DATABASE_NAME=Gatam.${ENVIRONMENT}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - SA_PASSWORD=${SA_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - TOKEN=${TOKEN}
      - BASE_URI=${BASE_URI}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENTID=${AUTH0_CLIENTID}
      - AUTH0_CLIENTSECRET=${AUTH0_CLIENTSECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    depends_on:
      - webapi
      - mssql-server
    networks:
      - database
      - production-proxy
  webappvolger:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAppVolger/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-webappvolger
    ports:
      - "8080"
      - "443"
    depends_on:
      - webapi
      - mssql-server
    networks:
      - database
      - production-proxy
volumes:
  sql_data:
networks:
  database:
  production-proxy:
    driver: bridge 
    external: true