services:
  mssql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: ${ENVIRONMENT}-mssql
    restart: always
    ports: 
      - "1433"
    environment:
      - ACCEPT_EULA="Y"
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_NAME=Gatam.${ENVIRONMENT}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
    networks:
      - database
    hostname: mssqlserver
  webapi:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAPI/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-api
    ports:
      - "8080"
      - "443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_HOST=${ENVIRONMENT}-mssql,1433
      - DATABASE_NAME=Gatam.${ENVIRONMENT}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - SA_PASSWORD=${SA_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - TOKEN=${TOKEN}
      - BASE_URI=${BASE_URI}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
    depends_on:
      - mssql-server
    networks:
      - database
      - proxy
  webappbegeleider:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAppBegeleider/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-webappbegeleider
    ports:
      - "8080"
      - "443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ENVIRONMENT=${ENVIRONMENT}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENTID=${AUTH0_CLIENTID}
      - AUTH0_CLIENTSECRET=${AUTH0_CLIENTSECRET}
    depends_on:
      - webapi
      - mssql-server
    networks:
      - database
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.staging-webappbegeleider.entrypoints=http"
      - "traefik.http.routers.staging-webappbegeleider.rule=Host(`staging-gatam-beheer.nilsvanvaerenbergh.be`)"
      - "traefik.http.middlewares.staging-webappbegeleider-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.staging-webappbegeleider.middlewares=staging-webappbegeleider-https-redirect"
      - "traefik.http.routers.staging-webappbegeleider-secure.entrypoints=https"
      - "traefik.http.routers.staging-webappbegeleider-secure.rule=Host(`staging-gatam-beheer.nilsvanvaerenbergh.be`)"
      - "traefik.http.routers.staging-webappbegeleider-secure.tls=true"
      - "traefik.http.routers.staging-webappbegeleider-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.staging-webappbegeleider-secure.tls.domains[0].main=nilsvanvaerenbergh.be"
      - "traefik.http.routers.staging-webappbegeleider-secure.tls.domains[0].sans=staging-gatam-beheer.nilsvanvaerenbergh.be"
  webappvolger:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAppVolger/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-webappvolger
    depends_on:
      - webapi
      - mssql-server
    networks:
      - database
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.staging-webappvolger.entrypoints=http"
      - "traefik.http.routers.staging-webappvolger.rule=Host(`staging-gatam.nilsvanvaerenbergh.be`)"
      - "traefik.http.middlewares.staging-webappvolger-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.staging-webappvolger.middlewares=staging-webappvolger-https-redirect"
      - "traefik.http.routers.staging-webappvolger-secure.entrypoints=https"
      - "traefik.http.routers.staging-webappvolger-secure.rule=Host(`staging-gatam.nilsvanvaerenbergh.be`)"
      - "traefik.http.routers.staging-webappvolger-secure.tls=true"
      - "traefik.http.routers.staging-webappvolger-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.staging-webappvolger-secure.tls.domains[0].main=nilsvanvaerenbergh.be"
      - "traefik.http.routers.staging-webappvolger-secure.tls.domains[0].sans=staging-gatam.nilsvanvaerenbergh.be"
volumes:
  sql_data:
networks:
  database:
  proxy:
    external: true 