services:
  mssql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: ${ENVIRONMENT}-mssql
    restart: always
    ports: 
      - "1433"
    environment:
      - ACCEPT_EULA="Y"
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_NAME=Gatam.${ENVIRONMENT}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
    networks:
      - database
    hostname: mssqlserver
  webapi:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAPI/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-api
    ports:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ENVIRONMENT=${ENVIRONMENT}
      - DATABASE_HOST=${ENVIRONMENT}-mssql,1433
      - DATABASE_NAME=Gatam.${ENVIRONMENT}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - SA_PASSWORD=${SA_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - TOKEN=${TOKEN}
      - BASE_URI=${BASE_URI}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
    depends_on:
      - mssql-server
    networks:
      - database
      - proxy
  webappbegeleider:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAppBegeleider/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-webappbegeleider
    ports:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ENVIRONMENT=${ENVIRONMENT}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENTID=${AUTH0_CLIENTID}
      - AUTH0_CLIENTSECRET=${AUTH0_CLIENTSECRET}
    depends_on:
      - webapi
      - mssql-server
    networks:
      - database
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.staging-webappbegeleider-http.entrypoints=http"
      - "traefik.http.routers.staging-webappbegeleider-http.rule=Host(`${ADMIN_DOMAIN}`)"
      - "traefik.http.routers.staging-webappbegeleider-http.middlewares=staging-webappbegeleider-redirect-to-https"
      - "traefik.http.middlewares.staging-webappbegeleider-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.staging-webappbegeleider-secure.entrypoints=https"
      - "traefik.http.routers.staging-webappbegeleider-secure.rule=Host(`${ADMIN_DOMAIN}`)"
      - "traefik.http.routers.staging-webappbegeleider-secure.tls=true"
      - "traefik.http.routers.staging-webappbegeleider-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.staging-webappbegeleider-secure.tls.domains[0].main=${ADMIN_DOMAIN}"
      - "traefik.http.routers.staging-webappbegeleider-secure.middlewares=sslheader"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.services.staging-webappbegeleider.loadbalancer.server.port=8080"
  webappvolger:
    build:
      context: .
      dockerfile: ./Presentation/Gatam.WebAppVolger/Dockerfile
    restart: always
    container_name: ${ENVIRONMENT}-webappvolger
    ports:
      - "8080"
    depends_on:
      - webapi
      - mssql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ENVIRONMENT=${ENVIRONMENT}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENTID=${AUTH0_CLIENTID}
      - AUTH0_CLIENTSECRET=${AUTH0_CLIENTSECRET}
    networks:
      - database
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.staging-webappvolger-http.entrypoints=http"
      - "traefik.http.routers.staging-webappvolger-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.staging-webappvolger-http.middlewares=staging-webappvolger-redirect-to-https"
      - "traefik.http.middlewares.staging-webappvolger-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.staging-webappvolger-secure.entrypoints=https"
      - "traefik.http.routers.staging-webappvolger-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.staging-webappvolger-secure.tls=true"
      - "traefik.http.routers.staging-webappvolger-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.staging-webappvolger-secure.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.staging-webappvolger-secure.middlewares=sslheader"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.services.staging-webappvolger.loadbalancer.server.port=8080"
volumes:
  sql_data:
networks:
  database:
  proxy:
    external: true 