FROM mcr.microsoft.com/dotnet/sdk:8.0 AS test

WORKDIR /source
ARG APP="Gatam.WebAPI"
COPY *.sln . 
COPY ../ApplicationCore/Gatam.Application/*.csproj ./ApplicationCore/Gatam.Application/
COPY ../ApplicationCore/Gatam.Domain/*.csproj ./ApplicationCore/Gatam.Domain/
COPY ../Infrastructure/Gatam.Infrastructure/*.csproj ./Infrastructure/Gatam.Infrastructure/
COPY ./${APP}/${APP}.csproj ./Presentation/${APP}/
RUN dotnet restore ./Presentation/${APP}/${APP}.csproj 
COPY ../. .
RUN dotnet test --no-restore --verbosity normal