version: '3.9'
services:
  proxy:
    build:
      dockerfile: Dockerfile
      context: . # The official v3 Traefik docker image
    restart: always
    ports:
       - "80:80"
       - "443:443"
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       - ./traefik.yml:/traefik.yml:ro
       - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    tty: true
    stdin_open: true
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    security_opt:
      - no-new-privileges:true
networks:
  proxy:
    external: true     
