version: '3.9'
services: 
  nginx:
    restart: always
    image: nginx:1-alpine-slim
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - production-proxy
      - staging-proxy
networks:
  production-proxy:
      driver: bridge
  staging-proxy:
      driver: bridge     
